import chroma from "chroma-js";

export default {
  ColorBox: {
    width: "20%",
    height: props => (props.showFullPalette ? "25%" : "50%"),
    margin: "-1px auto",
    display: "inline-block",
    position: "relative",
    marginBottom: "-3.5px",
    "&:hover button": {
      opacity: "1",
    },
  },
  copyText: {
    color: props => (chroma(props.background).luminance() >= 0.6 ? "#111" : "#eee"),
  },
  colorName: {
    color: props => (chroma(props.background).luminance() <= 0.1 ? "#eee" : "#111"),
  },
  seeMore: {
    color: props => (chroma(props.background).luminance() >= 0.6 ? "#111" : "#eee"),
    background: "rgba(255, 255, 255, 0.3)",
    position: "absolute",
    right: "0",
    bottom: "0",
    border: "none",
    width: "60px",
    height: "30px",
    textAlign: "center",
    lineHeight: "30px",
    textTransform: "uppercase",
    cursor: "pointer",
  },
  copyButton: {
    color: props => (chroma(props.background).luminance() >= 0.6 ? "#111" : "#eee"),
    width: "100px",
    height: "30px",
    position: "absolute",
    display: "inline-block",
    top: "50%",
    left: "50%",
    marginLeft: "-50px",
    marginTop: "-15px",
    outline: "none",
    textAlign: "center",
    background: "rgba(255, 255, 255, 0.3)",
    fontSize: "1rem",
    border: "none",
    transition: "0.4s",
    cursor: "pointer",
    textTransform: "uppercase",
    zIndex: "2",
    opacity: "0",
  },
  boxContent: {
    position: "absolute",
    width: "100%",
    left: "0",
    bottom: "0",
    padding: "10px",
    color: "#111",
    letterSpacing: "1px",
    fontSize: "12px",
  },
  copyOverlay: {
    opacity: "0",
    zIndex: "0",
    width: "100%",
    height: "100%",
    transform: "scale(0.2)",
    transition: "transform 0.5s ease-in-out",
  },
  showOverlay: {
    opacity: "1",
    transform: "scale(50)",
    zIndex: "10",
    position: "absolute",
  },
  copyMsg: {
    position: "fixed",
    left: "0",
    right: "0",
    top: "0",
    bottom: "0",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "3.5rem",
    transform: "scale(0.1)",
    opacity: "0",
    color: " #fff",
    zIndex: "0",
    "& h1": {
      fontWeight: "400",
      textShadow: "1px 2px 3px rgba(0, 0, 0, 0.4)",
      background: "rgba(255, 255, 255, 0.2)",
      width: "100%",
      textAlign: "center",
      marginBottom: "0",
      padding: "1rem",
      textTransform: "uppercase",
    },
    "& p": {
      fontSize: "2rem",
      fontWeight: "100",
    },
  },
  showMsg: {
    opacity: "1",
    transform: "scale(1)",
    zIndex: "15",
    transition: "all 0.4s ease-in-out",
    transitionDelay: "0.2s",
  },
};
