export default {
  Palette: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    overflowX: "hidden",
  },
  colors: {
    height: "90%",
  },
  goBack: {
    width: "20%",
    height: props => (props.showFullPalette ? "25%" : "50%"),
    margin: "-1px auto",
    display: "inline-block",
    position: "relative",
    marginBottom: "-3.5px",
    opacity: "1",
    backgroundColor: "#111",
    "& a": {
      width: "100px",
      height: "30px",
      position: "absolute",
      display: "inline-block",
      top: "50%",
      left: "50%",
      marginLeft: "-50px",
      marginTop: "-15px",
      outline: "none",
      textAlign: "center",
      background: "rgba(255, 255, 255, 0.3)",
      fontSize: "1rem",
      color: "#fff",
      border: "none",
      transition: "0.4s",
      cursor: "pointer",
      textTransform: "uppercase",
      zIndex: "2",
      textDecoration: "none",
      lineHeight: "1.6rem",
    },
  },
};
